name       : haskell-boundedchan
version    : 1.0.3.0
release    : 2
source     :
    - http://hackage.haskell.org/package/BoundedChan-1.0.3.0/BoundedChan-1.0.3.0.tar.gz : 531ceaed7f62844c2a63a7cbfdcab332ea5eaa218e9922ca3305580438adc46d
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library introduces BoundedChan. BoundedChans differ from Chans in
    that they are guaranteed to contain no more than a certain number of elements.
description: |
    This library introduces BoundedChan. BoundedChans differ from Chans in that they are guaranteed to contain no more than a certain number of elements.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
